#!/bin/bash


#http://stackoverflow.com/questions/8653126/how-to-increment-version-number-in-a-shell-script
increment_version ()
{
  declare -a part=( ${1//\./ } )
  declare    new
  declare -i carry=1

  for (( CNTR=${#part[@]}-1; CNTR>=0; CNTR-=1 )); do
    len=${#part[CNTR]}
    new=$((part[CNTR]+carry))
    [ ${#new} -gt $len ] && carry=1 || carry=0
    [ $CNTR -gt 0 ] && part[CNTR]=${new: -len} || part[CNTR]=${new}
  done
  new="${part[*]}"
  echo -e "${new// /.}"
}


if [ ! -f platform-details.h ]
then
    exit
fi

GIT_VERSION=$(git describe --abbrev=0 --tags)
CODE_VERSION=$(cat platform-details.h | grep APP_BUILD_VERSION | grep '#define' | sed -E 's/^.*\"(.*)\".*/\1/')

if [ -n "$(echo ${CODE_VERSION} | grep SNAPSHOT)" ]
then
 echo "Commited SNAPSHOT version: ${CODE_VERSION}"
else
    if [ "${GIT_VERSION}" != "${CODE_VERSION}" ]
    then
	git tag -a ${CODE_VERSION} -m "Setting ${CODE_VERSION}"
	echo "Commited NEW version: ${CODE_VERSION}"
    fi
    
    CODE_VERSION=$(increment_version ${CODE_VERSION})
    sed -i -E "s/#define\s*APP_BUILD_VERSION\s*\"(.*)\"/#define APP_BUILD_VERSION \"${CODE_VERSION}-SNAPSHOT\"/" platform-details.h
    git add platform-details.h
    git commit -m "Creating development version: ${CODE_VERSION}-SNAPSHOT"
fi

